/*
==============================================
Typescript definitions for v4.5.2
==============================================

This file was automatically generated by Papyrus-2-Typescript.exe
https://github.com/CarlosLeyvaAyala/Papyrus-2-Typescript

The program has no way to know the intention of the humans that made
the scripts, so it's always advisable to manually check all generated
files to make sure everything is declared as it should.

Take note the program assumes this script exists in some subfolder
to the folder where `skyrimPlatform.ts` is found, otherwise you'll get
"Cannot find module..." type of errors.

If you want to have this script in some other place, just change the
relative path of each `import`.
*/

import * as sp from "../skyrimPlatform"
import { Quest } from "../skyrimPlatform"
import { Form } from "../skyrimPlatform"

const sn = (sp as any).PO3_Events_Form

//EVENTS SHOULD BE CALLED ON A FORM

//ACTOR KILL [DEPRECATED - use alias or active effect]
	
export const RegisterForActorKilled = (akForm: Form | null | undefined): void => sn.RegisterForActorKilled(akForm)
export const UnregisterForActorKilled = (akForm: Form | null | undefined): void => sn.UnregisterForActorKilled(akForm)
	
// 	Event OnActorKilled(Actor akVictim, Actor akKiller)
// 	endEvent
	
//ACTOR REANIMATE [DEPRECATED - use alias or active effect]
	
export const RegisterForActorReanimateStart = (akForm: Form | null | undefined): void => sn.RegisterForActorReanimateStart(akForm)
export const UnregisterForActorReanimateStart = (akForm: Form | null | undefined): void => sn.UnregisterForActorReanimateStart(akForm)
	
export const RegisterForActorReanimateStop = (akForm: Form | null | undefined): void => sn.RegisterForActorReanimateStop(akForm)
export const UnregisterForActorReanimateStop = (akForm: Form | null | undefined): void => sn.UnregisterForActorReanimateStop(akForm)
	
// 	Event OnActorReanimateStart(Actor akTarget, Actor akCaster)
// 	endEvent
	
// 	Event OnActorReanimateStop(Actor akTarget, Actor akCaster)
// 	endEvent		
	
//ACTOR RESURRECT [DEPRECATED - use alias or active effect]
	
export const RegisterForActorResurrected = (akForm: Form | null | undefined): void => sn.RegisterForActorResurrected(akForm)
export const UnregisterForActorResurrected = (akForm: Form | null | undefined): void => sn.UnregisterForActorResurrected(akForm)
	
// 	Event OnActorResurrected(Actor akTarget, bool abResetInventory)
// 	endEvent
	
//BOOKS READ
	
export const RegisterForBookRead = (akForm: Form | null | undefined): void => sn.RegisterForBookRead(akForm)
export const UnregisterForBookRead = (akForm: Form | null | undefined): void => sn.UnregisterForBookRead(akForm)
	
// 	Event OnBookRead(Book akBook)
// 	endEvent

//CELL FULLY LOADED
//Can fire multiple times in exteriors, for each cell that is fully loaded.
	
export const RegisterForCellFullyLoaded = (akForm: Form | null | undefined): void => sn.RegisterForCellFullyLoaded(akForm)
export const UnregisterForCellFullyLoaded = (akForm: Form | null | undefined): void => sn.UnregisterForCellFullyLoaded(akForm)
	
// 	Event OnCellFullyLoaded(Cell akCell)
// 	endEvent
	
//CRITICAL HIT
//Player only event?
	
export const RegisterForCriticalHit = (akForm: Form | null | undefined): void => sn.RegisterForCriticalHit(akForm)
export const UnregisterForCriticalHit = (akForm: Form | null | undefined): void => sn.UnregisterForCriticalHit(akForm)
	
// 	Event OnCriticalHit(Actor akAggressor, Weapon akWeapon, bool abSneakHit)
// 	endEvent
	
//DISARMED
	
export const RegisterForDisarmed = (akForm: Form | null | undefined): void => sn.RegisterForDisarmed(akForm)
export const UnregisterForDisarmed = (akForm: Form | null | undefined): void => sn.UnregisterForDisarmed(akForm)
	
// 	Event OnDisarmed(Actor akSource, Weapon akTarget)
// 	endEvent
	
//DRAGON SOUL ABSORBED
	
export const RegisterForDragonSoulGained = (akForm: Form | null | undefined): void => sn.RegisterForDragonSoulGained(akForm)
export const UnregisterForDragonSoulGained = (akForm: Form | null | undefined): void => sn.UnregisterForDragonSoulGained(akForm)
	
// 	Event OnDragonSoulGained(float afSouls)
// 	endEvent
	
//ITEM HARVESTED
//Player only event
	
export const RegisterForItemHarvested = (akForm: Form | null | undefined): void => sn.RegisterForItemHarvested(akForm)
export const UnregisterForItemHarvested = (akForm: Form | null | undefined): void => sn.UnregisterForItemHarvested(akForm)
	
// 	Event OnItemHarvested(Form akProduce)
// 	endEvent
	
//LEVEL INCREASE
	
export const RegisterForLevelIncrease = (akForm: Form | null | undefined): void => sn.RegisterForLevelIncrease(akForm)
export const UnregisterForLevelIncrease = (akForm: Form | null | undefined): void => sn.UnregisterForLevelIncrease(akForm)
	
// 	Event OnLevelIncrease(int aiLevel)
// 	endEvent
	
//LOCATION DISCOVERY
	
export const RegisterForLocationDiscovery = (akForm: Form | null | undefined): void => sn.RegisterForLocationDiscovery(akForm)
export const UnregisterForLocationDiscovery = (akForm: Form | null | undefined): void => sn.UnregisterForLocationDiscovery(akForm)
	
// 	Event OnLocationDiscovery(String asRegionName, String asWorldspaceName)
// 	endEvent
		
//OBJECT GRAB/RELEASE
//Doesn't work with telekinesis and when the player grabs the same object in a row

export const RegisterForObjectGrab = (akForm: Form | null | undefined): void => sn.RegisterForObjectGrab(akForm)
export const UnregisterForObjectGrab = (akForm: Form | null | undefined): void => sn.UnregisterForObjectGrab(akForm)
	
// 	Event OnObjectGrab(ObjectReference akObjectRef)
// 	endEvent
	
// 	Event OnObjectRelease(ObjectReference akObjectRef)
// 	endEvent	
		
//OBJECT LOADED/UNLOADED
//Not all objects fire this event. It is somewhat inconsistent.

export const RegisterForObjectLoaded = (akForm: Form | null | undefined, formType: number): void => sn.RegisterForObjectLoaded(akForm,  formType)
export const UnregisterForObjectLoaded = (akForm: Form | null | undefined, formType: number): void => sn.UnregisterForObjectLoaded(akForm,  formType)
export const UnregisterForAllObjectsLoaded = (akForm: Form | null | undefined): void => sn.UnregisterForAllObjectsLoaded(akForm)
		
// 	Event OnObjectLoaded(ObjectReference akRef, int aiFormType)
// 	endEvent
	
// 	Event OnObjectUnloaded(ObjectReference akRef, int aiFormType)
// 	endEvent	
	
//QUEST START/STOP

export const RegisterForQuest = (akForm: Form | null | undefined, akQuest: Quest | null | undefined): void => sn.RegisterForQuest(akForm,  akQuest)
export const UnregisterForQuest = (akForm: Form | null | undefined, akQuest: Quest | null | undefined): void => sn.UnregisterForQuest(akForm,  akQuest)
export const UnregisterForAllQuests = (akForm: Form | null | undefined): void => sn.UnregisterForAllQuests(akForm)
	
// 	Event OnQuestStart(Quest akQuest)
// 	endEvent
	
// 	Event OnQuestStop(Quest akQuest)
// 	endEvent
	
//QUEST STAGE CHANGE

export const RegisterForQuestStage = (akForm: Form | null | undefined, akQuest: Quest | null | undefined): void => sn.RegisterForQuestStage(akForm,  akQuest)
export const UnregisterForQuestStage = (akForm: Form | null | undefined, akQuest: Quest | null | undefined): void => sn.UnregisterForQuestStage(akForm,  akQuest)
export const UnregisterForAllQuestStages = (akForm: Form | null | undefined): void => sn.UnregisterForAllQuestStages(akForm)
	
// 	Event OnQuestStageChange(Quest akQuest, Int aiNewStage)
// 	endEvent
	
//SHOUT ATTACK
//Player only event

export const RegisterForShoutAttack = (akForm: Form | null | undefined): void => sn.RegisterForShoutAttack(akForm)
export const UnregisterForShoutAttack = (akForm: Form | null | undefined): void => sn.UnregisterForShoutAttack(akForm)
	
// 	Event OnShoutAttack(Shout akShout)
// 	endEvent
	
//SKILL INCREASE

export const RegisterForSkillIncrease = (akForm: Form | null | undefined): void => sn.RegisterForSkillIncrease(akForm)
export const UnregisterForSkillIncrease = (akForm: Form | null | undefined): void => sn.UnregisterForSkillIncrease(akForm)
	
// 	Event OnSkillIncrease(String asSkill)
// 	endEvent
	
//SOUL TRAP
//Event will fire after OnDying/OnDeath

export const RegisterForSoulTrapped = (akForm: Form | null | undefined): void => sn.RegisterForSoulTrapped(akForm)
export const UnregisterForSoulTrapped = (akForm: Form | null | undefined): void => sn.UnregisterForSoulTrapped(akForm)
		
// 	Event OnSoulTrapped(Actor akVictim, Actor akKiller)
// 	endEvent
	
//SPELL LEARNED

export const RegisterForSpellLearned = (akForm: Form | null | undefined): void => sn.RegisterForSpellLearned(akForm)
export const UnregisterForSpellLearned = (akForm: Form | null | undefined): void => sn.UnregisterForSpellLearned(akForm)
		
// 	Event OnSpellLearned(Spell akSpell)
// 	endEvent
	
//WEATHER CHANGE

export const RegisterForWeatherChange = (akForm: Form | null | undefined): void => sn.RegisterForWeatherChange(akForm)
export const UnregisterForWeatherChange = (akForm: Form | null | undefined): void => sn.UnregisterForWeatherChange(akForm)
		
// 	Event OnWeatherChange(Weather akOldWeather, Weather akNewWeather)
// 	endEvent
	
//FEC - RESET ACTOR EFFECTS

export const RegisterForFECReset = (akForm: Form | null | undefined, aiType: number): void => sn.RegisterForFECReset(akForm,  aiType)
export const UnregisterForFECReset = (akForm: Form | null | undefined, aiType: number): void => sn.UnregisterForFECReset(akForm,  aiType)
export const UnregisterForAllFECResets = (akForm: Form | null | undefined): void => sn.UnregisterForAllFECResets(akForm)
		
// 	Event OnFECReset(Actor akActor, int aiType, bool abReset3D)
// 	endEvent
	
