/*
==============================================
Typescript definitions for v5.1
==============================================

***********************************************************************
 
This file was automatically generated by Papyrus-2-Typescript.exe
https://github.com/CarlosLeyvaAyala/Papyrus-2-Typescript

The program has no way to know the intention of the humans that made
the scripts, so it's always advisable to manually check all generated
files to make sure everything is declared as it should.
*/

import * as sp from "skyrimPlatform"

import { ActiveMagicEffect } from "skyrimPlatform"
import { Form } from "skyrimPlatform"
import { Quest } from "skyrimPlatform"

const sn = (sp as any).PO3_Events_AME

/** EVENTS SHOULD BE CALLED ON AN ACTIVEFFECT - script that is attached to a magic effect.
* DOCUMENTATION IS AVAILABLE AT https://github.com/powerof3/PapyrusExtenderSSE/wiki
* ACTOR FALL LONG DISTANCE
*/
	
export const RegisterForActorFallLongDistance = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForActorFallLongDistance(akActiveEffect)
export const UnregisterForActorFallLongDistance = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForActorFallLongDistance(akActiveEffect)

//ACTOR KILL
	
export const RegisterForActorKilled = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForActorKilled(akActiveEffect)
export const UnregisterForActorKilled = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForActorKilled(akActiveEffect)

//ACTOR REANIMATE
	
export const RegisterForActorReanimateStart = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForActorReanimateStart(akActiveEffect)
export const UnregisterForActorReanimateStart = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForActorReanimateStart(akActiveEffect)
	
export const RegisterForActorReanimateStop = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForActorReanimateStop(akActiveEffect)
export const UnregisterForActorReanimateStop = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForActorReanimateStop(akActiveEffect)

//ACTOR RESURRECT
	
export const RegisterForActorResurrected = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForActorResurrected(akActiveEffect)
export const UnregisterForActorResurrected = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForActorResurrected(akActiveEffect)

//BOOKS READ
	
export const RegisterForBookRead = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForBookRead(akActiveEffect)
export const UnregisterForBookRead = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForBookRead(akActiveEffect)

//CELL FULLY LOADED
	
export const RegisterForCellFullyLoaded = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForCellFullyLoaded(akActiveEffect)
export const UnregisterForCellFullyLoaded = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForCellFullyLoaded(akActiveEffect)

//CRITICAL HIT

export const RegisterForCriticalHit = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForCriticalHit(akActiveEffect)
export const UnregisterForCriticalHit = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForCriticalHit(akActiveEffect)

//DISARMED
	
export const RegisterForDisarmed = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForDisarmed(akActiveEffect)
export const UnregisterForDisarmed = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForDisarmed(akActiveEffect)

//DRAGON SOUL ABSORBED
	
export const RegisterForDragonSoulGained = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForDragonSoulGained(akActiveEffect)
export const UnregisterForDragonSoulGained = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForDragonSoulGained(akActiveEffect)

//ON HIT EX

export const RegisterForHitEventEx = (akActiveEffect: ActiveMagicEffect | null, akAggressorFilter: Form | null = null, akSourceFilter: Form | null = null, akProjectileFilter: Form | null = null, aiPowerFilter: number = -1, aiSneakFilter: number = -1, aiBashFilter: number = -1, aiBlockFilter: number = -1, abMatch: boolean = true): void => sn.RegisterForHitEventEx(akActiveEffect, akAggressorFilter, akSourceFilter, akProjectileFilter, aiPowerFilter, aiSneakFilter, aiBashFilter, aiBlockFilter, abMatch)
	
export const UnregisterForHitEventEx = (akActiveEffect: ActiveMagicEffect | null, akAggressorFilter: Form | null = null, akSourceFilter: Form | null = null, akProjectileFilter: Form | null = null, aiPowerFilter: number = -1, aiSneakFilter: number = -1, aiBashFilter: number = -1, aiBlockFilter: number = -1, abMatch: boolean = true): void => sn.UnregisterForHitEventEx(akActiveEffect, akAggressorFilter, akSourceFilter, akProjectileFilter, aiPowerFilter, aiSneakFilter, aiBashFilter, aiBlockFilter, abMatch)
	
export const UnregisterForAllHitEventsEx = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForAllHitEventsEx(akActiveEffect)

//ITEM CRAFTED

export const RegisterForItemCrafted = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForItemCrafted(akActiveEffect)
export const UnregisterForItemCrafted = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForItemCrafted(akActiveEffect)

//ITEM HARVESTED
	
export const RegisterForItemHarvested = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForItemHarvested(akActiveEffect)
export const UnregisterForItemHarvested = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForItemHarvested(akActiveEffect)

//LEVEL INCREASE
	
export const RegisterForLevelIncrease = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForLevelIncrease(akActiveEffect)
export const UnregisterForLevelIncrease = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForLevelIncrease(akActiveEffect)

//LOCATION DISCOVERY
	
export const RegisterForLocationDiscovery = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForLocationDiscovery(akActiveEffect)
export const UnregisterForLocationDiscovery = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForLocationDiscovery(akActiveEffect)

//OBJECT GRAB/RELEASE

export const RegisterForObjectGrab = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForObjectGrab(akActiveEffect)
export const UnregisterForObjectGrab = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForObjectGrab(akActiveEffect)

//OBJECT LOADED/UNLOADED

export const RegisterForObjectLoaded = (akActiveEffect: ActiveMagicEffect | null, formType: number): void => sn.RegisterForObjectLoaded(akActiveEffect, formType)
export const UnregisterForObjectLoaded = (akActiveEffect: ActiveMagicEffect | null, formType: number): void => sn.UnregisterForObjectLoaded(akActiveEffect, formType)
export const UnregisterForAllObjectsLoaded = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForAllObjectsLoaded(akActiveEffect)

//QUEST START/STOP

export const RegisterForQuest = (akActiveEffect: ActiveMagicEffect | null, akQuest: Quest | null): void => sn.RegisterForQuest(akActiveEffect, akQuest)
export const UnregisterForQuest = (akActiveEffect: ActiveMagicEffect | null, akQuest: Quest | null): void => sn.UnregisterForQuest(akActiveEffect, akQuest)
export const UnregisterForAllQuests = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForAllQuests(akActiveEffect)

//QUEST STAGE CHANGE

export const RegisterForQuestStage = (akActiveEffect: ActiveMagicEffect | null, akQuest: Quest | null): void => sn.RegisterForQuestStage(akActiveEffect, akQuest)
export const UnregisterForQuestStage = (akActiveEffect: ActiveMagicEffect | null, akQuest: Quest | null): void => sn.UnregisterForQuestStage(akActiveEffect, akQuest)
export const UnregisterForAllQuestStages = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForAllQuestStages(akActiveEffect)

//SHOUT ATTACK

export const RegisterForShoutAttack = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForShoutAttack(akActiveEffect)
export const UnregisterForShoutAttack = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForShoutAttack(akActiveEffect)

//SKILL INCREASE

export const RegisterForSkillIncrease = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForSkillIncrease(akActiveEffect)
export const UnregisterForSkillIncrease = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForSkillIncrease(akActiveEffect)

//SOUL TRAP

export const RegisterForSoulTrapped = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForSoulTrapped(akActiveEffect)
export const UnregisterForSoulTrapped = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForSoulTrapped(akActiveEffect)

//SPELL LEARNED

export const RegisterForSpellLearned = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForSpellLearned(akActiveEffect)
export const UnregisterForSpellLearned = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForSpellLearned(akActiveEffect)

//WEATHER CHANGE

export const RegisterForWeatherChange = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForWeatherChange(akActiveEffect)
export const UnregisterForWeatherChange = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForWeatherChange(akActiveEffect)

//MAGIC EFFECT APPLY

export const RegisterForMagicEffectApplyEx = (akActiveEffect: ActiveMagicEffect | null, akEffectFilter: Form | null, abMatch: boolean): void => sn.RegisterForMagicEffectApplyEx(akActiveEffect, akEffectFilter, abMatch)
export const UnregisterForMagicEffectApplyEx = (akActiveEffect: ActiveMagicEffect | null, akEffectFilter: Form | null, abMatch: boolean): void => sn.UnregisterForMagicEffectApplyEx(akActiveEffect, akEffectFilter, abMatch)
export const UnregisterForAllMagicEffectApplyEx = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForAllMagicEffectApplyEx(akActiveEffect)

//ON WEAPON HIT
	
export const RegisterForWeaponHit = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForWeaponHit(akActiveEffect)
export const UnregisterForWeaponHit = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForWeaponHit(akActiveEffect)

//ON MAGIC HIT

export const RegisterForMagicHit = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForMagicHit(akActiveEffect)
export const UnregisterForMagicHit = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForMagicHit(akActiveEffect)

//ON PROJECTILE HIT

export const RegisterForProjectileHit = (akActiveEffect: ActiveMagicEffect | null): void => sn.RegisterForProjectileHit(akActiveEffect)
export const UnregisterForProjectileHit = (akActiveEffect: ActiveMagicEffect | null): void => sn.UnregisterForProjectileHit(akActiveEffect)
